version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbtest
    ports:
      - "15432:5432"
    networks:
      - app-network  # Add network here

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./../src/:/var/www
    networks:
      - app-network  # Add network here

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../src/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network  # Add network here

  react:
    container_name: react
    build: 
      context: ./../src/public/ecommerce
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      -  ./../src/public/ecommerce:/app
    networks:
      - app-network  # Add network here

networks:
  app-network:
    driver: bridge
